version: "6.10"
policies:
  - fields:
      - localip
      - grouping
  - fields:
      - tenantid
      - jobid
      - grouping
  - fields:
      - tenantid
      - localip
      - grouping
  - fields:
      - localip
      - remoteip
